### ISSUE TITLE
ReadAPI shows error concerning CoAP requests - CoapRequestTestStepPanel.getSubmitButton error

### ISSUE THREAD

**Issue by dvsilva** [SmartBear/readyapi-coap-plugin#4]
ReadAPI shows error concerning CoAP requests.
The following error is exhibited:

Tue Sep 24 20:53:03 BRT 2019: ERROR: java.lang.reflect.UndeclaredThrowableException
   java.lang.reflect.UndeclaredThrowableException
   	at com.sun.proxy.$Proxy61.buildDesktopPanel(Unknown Source)
   	at com.eviware.soapui.ready.SinglePanelDesktop.a(SinglePanelDesktop.java:151)
   	at com.eviware.soapui.ready.SinglePanelDesktop.showDesktopPanel(SinglePanelDesktop.java:130)
   	at com.eviware.soapui.ui.HistoryAwareDesktop.showDesktopPanel(HistoryAwareDesktop.java:158)
   	at com.eviware.soapui.ready.ClassicModuleGui.display(ClassicModuleGui.java:197)
   	at com.smartbear.ready.core.module.SimpleReadyApiDisplayDispatcher.display(SimpleReadyApiDisplayDispatcher.java:90)
   	at com.smartbear.ready.core.module.SimpleReadyApiDisplayDispatcher.display(SimpleReadyApiDisplayDispatcher.java:85)
   	at com.eviware.soapui.support.UISupport.selectAndShow(UISupport.java:1352)
   	at com.eviware.soapui.support.UISupport.selectAndShow(UISupport.java:1338)
   	at com.eviware.soapui.impl.wsdl.actions.support.ShowDesktopPanelAction.perform(ShowDesktopPanelAction.java:50)
   	at com.eviware.soapui.support.action.swing.SwingActionDelegate.actionPerformed(SwingActionDelegate.java:129)
   	at com.eviware.soapui.support.action.swing.DefaultActionList.performDefaultAction(DefaultActionList.java:97)
   	at com.eviware.soapui.ui.TreeMouseListener$1.run(TreeMouseListener.java:152)
   	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
   	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
   	at java.awt.EventQueue.access$500(Unknown Source)
   	at java.awt.EventQueue$3.run(Unknown Source)
   	at java.awt.EventQueue$3.run(Unknown Source)
   	at java.security.AccessController.doPrivileged(Native Method)
   	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
   	at java.awt.EventQueue.dispatchEvent(Unknown Source)
   	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
   	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
   	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
   	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
   	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
   	at java.awt.EventDispatchThread.run(Unknown Source)
   Caused by: java.lang.reflect.InvocationTargetException
   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   	at java.lang.reflect.Method.invoke(Unknown Source)
   	at com.eviware.soapui.plugins.PluginProxies$DelegatingHandler.invoke(PluginProxies.java:116)
   	... 27 more
   Caused by: java.lang.NoSuchMethodError: com.smartbear.coapsupport.CoapRequestTestStepPanel.getSubmitButton()Ljavax/swing/JButton;
   	at com.smartbear.coapsupport.CoapRequestTestStepPanel.buildContent(CoapRequestTestStepPanel.java:158)
   	at com.eviware.soapui.impl.support.panels.AbstractHttpRequestDesktopPanel.init(AbstractHttpRequestDesktopPanel.java:292)
   	at com.eviware.soapui.impl.support.panels.AbstractHttpRequestDesktopPanel.<init>(AbstractHttpRequestDesktopPanel.java:166)
   	at com.eviware.soapui.impl.support.panels.AbstractHttpXmlRequestDesktopPanel.<init>(AbstractHttpXmlRequestDesktopPanel.java:47)
   	at com.smartbear.coapsupport.CoapRequestTestStepPanel.<init>(CoapRequestTestStepPanel.java:88)
   	at com.smartbear.coapsupport.CoapRequestTestStepPanelBuilder.buildDesktopPanel(CoapRequestTestStepPanelBuilder.java:15)
   	at com.smartbear.coapsupport.CoapRequestTestStepPanelBuilder.buildDesktopPanel(CoapRequestTestStepPanelBuilder.java:1)
   	... 32 more
Tue Sep 24 20:53:14 BRT 2019: ERROR: java.lang.reflect.UndeclaredThrowableException
   java.lang.reflect.UndeclaredThrowableException
   	at com.sun.proxy.$Proxy61.buildDesktopPanel(Unknown Source)
   	at com.eviware.soapui.ready.SinglePanelDesktop.a(SinglePanelDesktop.java:151)
   	at com.eviware.soapui.ready.SinglePanelDesktop.showDesktopPanel(SinglePanelDesktop.java:130)
   	at com.eviware.soapui.ui.HistoryAwareDesktop.showDesktopPanel(HistoryAwareDesktop.java:158)
   	at com.eviware.soapui.ready.ClassicModuleGui.display(ClassicModuleGui.java:197)
   	at com.smartbear.ready.core.module.SimpleReadyApiDisplayDispatcher.display(SimpleReadyApiDisplayDispatcher.java:90)
   	at com.smartbear.ready.core.module.SimpleReadyApiDisplayDispatcher.display(SimpleReadyApiDisplayDispatcher.java:85)
   	at com.eviware.soapui.support.UISupport.selectAndShow(UISupport.java:1352)
   	at com.eviware.soapui.support.UISupport.selectAndShow(UISupport.java:1338)
   	at com.eviware.soapui.impl.wsdl.actions.support.ShowDesktopPanelAction.perform(ShowDesktopPanelAction.java:50)
   	at com.eviware.soapui.support.action.swing.SwingActionDelegate.actionPerformed(SwingActionDelegate.java:129)
   	at com.eviware.soapui.support.action.swing.DefaultActionList.performDefaultAction(DefaultActionList.java:97)
   	at com.eviware.soapui.ui.TreeMouseListener$1.run(TreeMouseListener.java:152)
   	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
   	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
   	at java.awt.EventQueue.access$500(Unknown Source)
   	at java.awt.EventQueue$3.run(Unknown Source)
   	at java.awt.EventQueue$3.run(Unknown Source)
   	at java.security.AccessController.doPrivileged(Native Method)
   	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
   	at java.awt.EventQueue.dispatchEvent(Unknown Source)
   	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
   	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
   	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
   	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
   	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
   	at java.awt.EventDispatchThread.run(Unknown Source)
   Caused by: java.lang.reflect.InvocationTargetException
   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   	at java.lang.reflect.Method.invoke(Unknown Source)
   	at com.eviware.soapui.plugins.PluginProxies$DelegatingHandler.invoke(PluginProxies.java:116)
   	... 27 more
   Caused by: java.lang.NoSuchMethodError: com.smartbear.coapsupport.CoapRequestTestStepPanel.getSubmitButton()Ljavax/swing/JButton;
   	at com.smartbear.coapsupport.CoapRequestTestStepPanel.buildContent(CoapRequestTestStepPanel.java:158)
   	at com.eviware.soapui.impl.support.panels.AbstractHttpRequestDesktopPanel.init(AbstractHttpRequestDesktopPanel.java:292)
   	at com.eviware.soapui.impl.support.panels.AbstractHttpRequestDesktopPanel.<init>(AbstractHttpRequestDesktopPanel.java:166)
   	at com.eviware.soapui.impl.support.panels.AbstractHttpXmlRequestDesktopPanel.<init>(AbstractHttpXmlRequestDesktopPanel.java:47)
   	at com.smartbear.coapsupport.CoapRequestTestStepPanel.<init>(CoapRequestTestStepPanel.java:88)
   	at com.smartbear.coapsupport.CoapRequestTestStepPanelBuilder.buildDesktopPanel(CoapRequestTestStepPanelBuilder.java:15)
   	at com.smartbear.coapsupport.CoapRequestTestStepPanelBuilder.buildDesktopPanel(CoapRequestTestStepPanelBuilder.java:1)
   	... 32 more

**Comment by dvsilva** [comment]
any information about it?

**Comment by IlyaAvdeev** [comment]
what ReadyAPI version do you use?

**Comment by dvsilva** [comment]
Thanks for the answer.
The newest. I've installed on more than one computer and the same problem was presented.

**Comment by dvsilva** [comment]
![Captura de tela de 2019-10-01 08-25-45](https://user-images.githubusercontent.com/15819565/65958613-2c062080-e426-11e9-8968-8430179b972e.png)

**Comment by IlyaAvdeev** [comment]
Hey, @dvsilva I've udpate the repo. Now you can build yourself as written in the repo readme.md. I'll some additional fixes soon.

**Comment by IlyaAvdeev** [comment]
upd: please let me know if plugin works for you or not.

**Comment by dvsilva** [comment]
very good, i've tried to build it before, but an error present.
I tried again today, and it buit!

one question, how can I install manually this?

**Comment by IlyaAvdeev** [comment]
just put it in your {USER_HOME_DIR}\.soapui\plugins
like below
![image](https://user-images.githubusercontent.com/7438227/66041531-b7fd7280-e522-11e9-8d5f-48ee79d8411a.png)

**Comment by dvsilva** [comment]
oh, an error present again while building it :/

![Captura de tela de 2019-10-02 08-41-52](https://user-images.githubusercontent.com/15819565/66041569-8966a400-e4f0-11e9-93a8-78a3078e119d.png)

**Comment by dvsilva** [comment]
could you upload here in github in "packages" ? :D

**Comment by IlyaAvdeev** [comment]
I will do very soon, just a small note - it seems you didn't pull the latest changes

**Comment by IlyaAvdeev** [comment]
according to the log output you pull artifacts from maven central instead of SoapUI repo. see the root pom

**Comment by dvsilva** [comment]
I clone from git by command line :/
what do you mean? in the maven folder ?
I am using ubuntu 18, then /root/.m2 ?
sorry I'm a starter programmer =)

**Comment by IlyaAvdeev** [comment]
just have updated the plugin into plugin repository, please uninstall (remove) the last one & install the new one again.

**Comment by dvsilva** [comment]
you are the man!
The described problem doesn't occur now!!
Thanks for your help!
![Captura de tela de 2019-10-02 09-42-34](https://user-images.githubusercontent.com/15819565/66044915-fe3ddc00-e4f8-11e9-9e9b-8da80144f5cc.png)

**Comment by IlyaAvdeev** [comment]
You're welcome! Closing the issue.
